version: "2"
services:

  # Postgresql Database
  db:
    image: "skalera/postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "finance"
      POSTGRES_PASSWORD: "finance"
      POSTGRES_DB: "finance"
